# Generated by Django 5.2.10 on 2026-02-13 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("nacionalidad", models.CharField(blank=True, max_length=50)),
                ("biografia", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Editorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("pais", models.CharField(max_length=50)),
                ("sitio_web", models.URLField(blank=True)),
                ("fecha_fundacion", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Editorial",
                "verbose_name_plural": "Editoriales",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("fecha_publicacion", models.DateField()),
                ("numero_paginas", models.IntegerField()),
                ("idioma", models.CharField(default="Español", max_length=50)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("prestado", "Prestado"),
                            ("reservado", "Reservado"),
                            ("mantenimiento", "En Mantenimiento"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("stock_total", models.IntegerField(default=1)),
                ("stock_disponible", models.IntegerField(default=1)),
                (
                    "ubicacion_fisica",
                    models.CharField(
                        blank=True, help_text="Ej: Estante A-12", max_length=50
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="libros",
                        to="libros.autor",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="libros",
                        to="libros.categoria",
                    ),
                ),
                (
                    "editorial",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="libros",
                        to="libros.editorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateField(auto_now_add=True)),
                ("fecha_devolucion_esperada", models.DateField()),
                ("fecha_devolucion_real", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("devuelto", "Devuelto"),
                            ("vencido", "Vencido"),
                            ("renovado", "Renovado"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("renovaciones", models.IntegerField(default=0)),
                (
                    "multa",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamos",
                        to="libros.libro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préstamo",
                "verbose_name_plural": "Préstamos",
                "ordering": ["-fecha_prestamo"],
            },
        ),
    ]
